container:
  image: node:buster
  memory: 8G

task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  build_folder_cache:
    folder: build
    fingerprint_script: cat scripts/build.sh

  matrix:
    - name: Build
      deps_script:
        - apt-get update
        - apt-get install -y p7zip-full
      build_script:
        - ./scripts/build.sh
        - ./scripts/build.sh arm64

    - name: Package DEB
      only_if: $CIRRUS_BRANCH == 'main'
      depends_on: Build
      deps_script:
        - apt-get update
        - apt-get install -y fakeroot
      package_script:
        - ./scripts/package-deb.sh &
        - ./scripts/package-deb.sh arm64 arm64 &
        - wait
      deb_artifacts:
        path: "out/*"

    - name: Package RPM
      only_if: $CIRRUS_BRANCH == 'main'
      depends_on: Build
      deps_script:
        - apt-get update
        - apt-get install -y rpm
      package_script:
        - ./scripts/package-rpm.sh &
        - ./scripts/package-rpm.sh arm64 aarch64 &
        - wait
      rpm_artifacts:
        path: "out/*"

    - name: Create RPM repo
      only_if: $CIRRUS_BRANCH == 'main'
      depends_on: Package RPM
      container:
        image: fedora:latest
      deps_script:
        - dnf install -y createrepo wget unzip
      create_repo_script:
        - wget -q https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/rpm.zip
        - unzip -j -d rpms rpm.zip
        - createrepo rpms
      rpm_repo_artifacts:
        path: "rpms/**/*"

    - name: Deploy to Netlify
      only_if: $CIRRUS_BRANCH == 'main'
      depends_on:
        - Create RPM repo
      environment:
        BUILD_HOOK_URL: ENCRYPTED[10dc237d88473e08358f0544c348a948827900f432407f329a1002297ba6a716b2f37bf40d527279e0f9cc2c2565657f]
      deploy_script: curl -X POST -d {} $BUILD_HOOK_URL
