container:
  image: davidbailey/notion-linux-builder

build_app_task:
  <<: &build_cache
    node_modules_cache:
      folder: node_modules
      fingerprint_script: cat package-lock.json
      populate_script: npm install
    build_folder_cache:
      folder: build
      fingerprint_script:
        - cat package-lock.json
        - cat scripts/build.sh
  build_app_script:
    - ./scripts/build.sh
    - ./scripts/build.sh arm64

package_deb_task:
  <<: *build_cache
  debs_cache: &debs_cache
    folder: out/debs
    fingerprint_script:
      - cat package-lock.json
      - cat scripts/build.sh
      - cat scripts/package-deb.sh
  depends_on: build_app
  package_deb_script:
    - ./scripts/package-deb.sh &
    - ./scripts/package-deb.sh arm64 arm64 &
    - wait

package_rpm_task:
  <<: *build_cache
  rpms_cache: &rpms_cache
    folder: out/rpms
    fingerprint_script:
      - cat package-lock.json
      - cat scripts/build.sh
      - cat scripts/package-rpm.sh
  depends_on: build_app
  container:
    memory: 6G
  package_rpm_script:
    - ./scripts/package-rpm.sh &
    - ./scripts/package-rpm.sh arm64 aarch64 &
    - wait

create_deb_repo_task:
  debs_cache: *debs_cache
  deb_repo_cache: &deb_repo_cache
    folder: out/deb_repo
    fingerprint_script: echo $CIRRUS_BUILD_ID
  only_if: $CIRRUS_BRANCH == 'main'
  depends_on: package_deb
  create_deb_repo_script:
    - aptly repo create notion-linux
    - aptly repo add notion-linux out/debs/*
    - aptly publish repo -skip-signing -distribution=stable notion-linux debs
    - cp -R ~/.aptly/public/debs out/deb_repo

create_rpm_repo_task:
  rpms_cache: *rpms_cache
  rpm_repo_cache: &rpm_repo_cache
    folder: out/rpm_repo
    fingerprint_script:
      - cat package-lock.json
      - cat scripts/build.sh
      - cat scripts/package-rpm.sh
  only_if: $CIRRUS_BRANCH == 'main'
  depends_on: package_rpm
  create_rpm_repo_script:
    - mkdir -p out/rpm_repo
    - cp out/rpms/* out/rpm_repo
    - createrepo --update out/rpm_repo

deploy_to_firebase_task:
  deb_repo_cache: *deb_repo_cache
  rpm_repo_cache: *rpm_repo_cache
  only_if: $CIRRUS_BRANCH == 'main'
  environment:
    FIREBASE_TOKEN: ENCRYPTED[f3ae7ef0f415d3221d39d7f4d7c6547ef1f78e588db1c5ba876d601eba3e524eff34d9af4058eed3a3339e7a0c63c44b]
  depends_on:
    - create_deb_repo
    - create_rpm_repo
  firebase_deploy_script:
    - cp -R out/deb_repo public/debs
    - cp -R out/rpm_repo public/rpms
    - firebase deploy --token "$FIREBASE_TOKEN"
