container:
  image: ghcr.io/davidbailey00/notion-linux

build_app_task:
  <<: &build_cache
    node_modules_cache:
      folder: node_modules
      fingerprint_script: cat package-lock.json
      populate_script: npm install
    build_folder_cache:
      folder: build
      fingerprint_script:
        - cat package-lock.json
        - cat scripts/{_variables-*,build,enhance}.sh
  build_app_script:
    - scripts/build.sh
    - scripts/build.sh -b arm64
  enhance_app_script:
    - scripts/enhance.sh
    - scripts/enhance.sh -b arm64

package_deb_task:
  <<: *build_cache
  debs_cache: &debs_cache
    folder: out/debs
    fingerprint_script:
      - cat package-lock.json
      - cat scripts/{_variables-*,build,enhance,package-deb}.sh
      - cat templates/desktop-deb.ejs
  depends_on: build_app
  container:
    cpu: 4
    memory: 10G
  package_deb_script:
    - scripts/package-deb.sh &
    - scripts/package-deb.sh -b arm64 &
    - scripts/package-deb.sh -n notion-enhanced &
    - scripts/package-deb.sh -n notion-enhanced -b arm64 &
    - wait
    - "[[ $(ls out/debs | wc -l) == 4 ]]"
  deb_artifacts:
    path: "out/debs/*"

package_rpm_task:
  <<: *build_cache
  rpms_cache: &rpms_cache
    folder: out/rpms
    fingerprint_script:
      - cat package-lock.json
      - cat scripts/{_variables-*,build,enhance,package-rpm}.sh
      - cat templates/desktop-rpm.ejs
  depends_on: build_app
  container:
    cpu: 4
  package_rpm_script:
    - scripts/package-rpm.sh &
    - scripts/package-rpm.sh -b arm64 &
    - scripts/package-rpm.sh -n notion-enhanced &
    - scripts/package-rpm.sh -n notion-enhanced -b arm64 &
    - wait
    - "[[ $(ls out/rpms | wc -l) == 4 ]]"
  rpm_artifacts:
    path: "out/rpms/*"

create_deb_repo_task:
  debs_cache: *debs_cache
  aptly_cache:
    folder: ~/.aptly
    fingerprint_script: echo aptly_cache
    reupload_on_changes: true
  deb_repo_cache: &deb_repo_cache
    folder: out/deb_repo
    fingerprint_script: echo $CIRRUS_BUILD_ID
  only_if: $CIRRUS_BRANCH == 'main'
  depends_on: package_deb
  create_deb_repo_script:
    - aptly repo create notion-linux || true
    - aptly repo add notion-linux out/debs/*
    - scripts/purge_old_versions.py notion-linux notion-desktop 2
    - scripts/purge_old_versions.py notion-linux notion-enhanced 2
    - aptly db cleanup
    - aptly publish repo -skip-signing -distribution=stable notion-linux debs ||
      aptly publish update -skip-signing -force-overwrite stable debs
    - cp -R ~/.aptly/public/debs out/deb_repo

create_rpm_repo_task:
  rpms_cache: *rpms_cache
  rpm_repo_cache: &rpm_repo_cache
    folder: out/rpm_repo
    fingerprint_script: echo rpm_repo_cache
    reupload_on_changes: true
  only_if: $CIRRUS_BRANCH == 'main'
  depends_on: package_rpm
  create_rpm_repo_script:
    - mkdir -p out/rpm_repo
    - cp out/rpms/* out/rpm_repo
    - rm $(repomanage --old --keep=2 out/rpm_repo)
    - createrepo --update --deltas --oldpackagedirs out/rpm_repo --max-delta-rpm-size 536870912 out/rpm_repo

deploy_to_firebase_task:
  deb_repo_cache: *deb_repo_cache
  rpm_repo_cache: *rpm_repo_cache
  only_if: $CIRRUS_BRANCH == 'main'
  environment:
    FIREBASE_TOKEN: ENCRYPTED[f3ae7ef0f415d3221d39d7f4d7c6547ef1f78e588db1c5ba876d601eba3e524eff34d9af4058eed3a3339e7a0c63c44b]
  depends_on:
    - create_deb_repo
    - create_rpm_repo
  firebase_deploy_script:
    - cp -R out/deb_repo public/debs
    - cp -R out/rpm_repo public/rpms
    - firebase deploy --token "$FIREBASE_TOKEN"
