image: node:buster

stages:
  - build
  - package
  - deploy

variables:
  NOTION_VERSION: 2.0.11
  PACKAGE_REVISION: 3

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y p7zip-full
    - ./build.sh
    - ./build.sh arm64
  artifacts:
    paths:
      - node_modules/
      - build/$NOTION_VERSION-$PACKAGE_REVISION-x64/app-linux-x64
      - build/$NOTION_VERSION-$PACKAGE_REVISION-arm64/app-linux-arm64
    expire_in: 1 hour

package:deb:
  stage: package
  script:
    - apt-get update
    - apt-get install -y fakeroot
    - ./package-deb.sh
    - ./package-deb.sh arm64 arm64
  artifacts:
    paths:
      - out/
    expire_in: 1 hour
  only: ["main"]

package:rpm:
  stage: package
  script:
    - apt-get update
    - apt-get install -y rpm
    - ./package-rpm.sh
    - ./package-rpm.sh arm64 aarch64
  artifacts:
    paths:
      - out/
    expire_in: 1 hour
  only: ["main"]
